// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsKTUyB7SQ7zCinEIqZL4WVCPkx0R6QhQ',
    appId: '1:106521195477:web:f87a7600489bf07603835c',
    messagingSenderId: '106521195477',
    projectId: 'gurukula-lms-mobile-app',
    authDomain: 'gurukula-lms-mobile-app.firebaseapp.com',
    storageBucket: 'gurukula-lms-mobile-app.appspot.com',
    measurementId: 'G-BEDFVP8L6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gbYqH4VWIxGOl9Rv_h7jR7pAQ0vjLdw',
    appId: '1:106521195477:android:c509bd3e4a7074cf03835c',
    messagingSenderId: '106521195477',
    projectId: 'gurukula-lms-mobile-app',
    storageBucket: 'gurukula-lms-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb1yIAt5Sb8l0PLcma9sbIfgAjUQxxkzM',
    appId: '1:106521195477:ios:149774a84d240a4403835c',
    messagingSenderId: '106521195477',
    projectId: 'gurukula-lms-mobile-app',
    storageBucket: 'gurukula-lms-mobile-app.appspot.com',
    iosClientId: '106521195477-2di3447fjhfdit3keh301jiifsm31hdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb1yIAt5Sb8l0PLcma9sbIfgAjUQxxkzM',
    appId: '1:106521195477:ios:149774a84d240a4403835c',
    messagingSenderId: '106521195477',
    projectId: 'gurukula-lms-mobile-app',
    storageBucket: 'gurukula-lms-mobile-app.appspot.com',
    iosClientId: '106521195477-2di3447fjhfdit3keh301jiifsm31hdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningManagement',
  );
}
